version: '3.4'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: instalika
      MYSQL_DATABASE: instalika
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./prekes.sql:/docker-entrypoint-initdb.d/prekes.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pinstalika"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    restart: always
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      mysql:
        condition: service_healthy
